# ----------- CONFIGURABLE START -----------
title:            "LiberXue|FullStack|独立开发者|jekyll blog|GitHub blog"
description:      "WINNING-PTS|欢迎来到技术文档「角落」侃侃理想、谈谈人生、敲敲代码。"
url:              https://lion-atom.github.io/tongminjie.github.io/ # 域名
signoff:          "Lion-Atom" # Your name
facebook_appid:   #liberxue
google_analytics: UA-101222464-1
share:            true 
# 分页
paginate: 15
paginate_path: "liberxuepage:num"
gems: [jekyll-paginate]
links:
  - name:         首页
    url:          /tongminjie.github.io/
    external:     false
  - name:         书籍
    url:          /tongminjie.github.io/book
    external:     false
  - name:         旅游
    url:          /tongminjie.github.io/road
    external:     false
  - name:         归档
    url:          /tongminjie.github.io/archives
    external:     false
  - name:         标签
    url:          /tongminjie.github.io/tags
    external:     false
  - name:         关于
    url:          /tongminjie.github.io/about
    external:     false
# ------------ CONFIGURABLE END ------------

#permalink:        /:categories/:title.html
permalink: /:year/:month/:day/:title.html
defaults:
  - values:
      layout: "default"
